[theme]
base = "light"
primaryColor = "#176B70"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182B40"
font = "sans serif"
[browser]
gatherUsageStats = false
[server]
address = "127.0.0.1"
headless = true
fileWatcherType = "none"
runOnSave = false
